development:
  adapter: mysql2
  encoding: utf8
  database: onlinemagzine
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: onlinemagzine
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000